{% set name = "drf-pydantic" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/drf_pydantic-{{ version }}.tar.gz
  sha256: 16c2dbead529311629f421bb360cf286a406878a5e882106a59876dc677666fe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pydantic >=2.0.0
    - djangorestframework >=3.13.0

test:
  imports:
    - drf_pydantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/georgebv/drf-pydantic
  summary: Use pydantic with the Django REST framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
