{% set name = "drf-pydantic" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/drf_pydantic-{{ version }}.tar.gz
  sha256: 8c731b5c65bba871812623c498d52ccd1754f1880e31258ca930f2c6568bcb9b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pydantic >=2.0.0
    - djangorestframework >=3.13.0

test:
  imports:
    - drf_pydantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/georgebv/drf-pydantic
  summary: Use pydantic with the Django REST framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
