{% set name = "drf-pydantic" %}
{% set version = "2.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/drf_pydantic-{{ version }}.tar.gz
  sha256: cf909c9120079d212ed71406f775e5c7005768205a247c75e9ae2ffaf10ecc25

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - pydantic >=2.0.0
    - djangorestframework >=3.13.0

test:
  imports:
    - drf_pydantic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/georgebv/drf-pydantic
  summary: Use pydantic with the Django REST framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
